"""Skill synonym data used by the formula-based analysis pipeline."""

SKILL_SYNONYMS = {
    "python": ["python", "py", "python3", "python programming"],
    "javascript": ["javascript", "js", "ecmascript", "es6", "es2015"],
    "java": ["java", "java programming"],
    "pandas": ["pandas", "pd"],
    "numpy": ["numpy", "np"],
    "react": ["react", "reactjs", "react.js"],
    "node.js": ["node", "nodejs", "node.js"],
    "sql": ["sql", "mysql", "postgresql", "postgres", "structured query language"],
    "machine learning": ["machine learning", "ml", "statistical learning"],
    "deep learning": ["deep learning", "dl", "neural networks"],
    "data visualization": ["data visualization", "visualization", "matplotlib", "seaborn", "plotly"],
    "statistics": ["statistics", "stats", "statistical analysis"],
    "scikit-learn": ["scikit-learn", "sklearn", "scikit learn"],
    "tensorflow": ["tensorflow", "tf"],
    "pytorch": ["pytorch", "torch"],
    "docker": ["docker", "containerization"],
    "kubernetes": ["kubernetes", "k8s"],
    "aws": ["aws", "amazon web services", "amazon aws"],
    "azure": ["azure", "microsoft azure"],
    "git": ["git", "github", "gitlab", "version control"],
    "rest api": ["rest", "rest api", "restful", "api"],
    "agile": ["agile", "scrum", "agile methodology"],
    "communication": ["communication", "communication skills", "verbal communication"],
    "ios": ["ios", "i os"],
    "swift": ["swift"],
    "xcode": ["xcode", "x code"],
    "objective c": ["objective c", "objective-c"],
    "cocoa touch": ["cocoa touch"],
    "sqlite": ["sqlite", "sql lite"],
    "json": ["json"],
    "xml": ["xml"],
    "soap": ["soap"],
    "android": ["android"],
    "kotlin": ["kotlin"],
    "firebase": ["firebase"],
    "react native": ["react native"],
    "flutter": ["flutter"],
    "mobile development": ["mobile development", "mobile app development"],
}

